### PR TITLE
Allow env vars

### PR DESCRIPTION
**Pull request by rlukata**
This PR changes the behavior of the action by allowing access key ID, secret access key, and region to be read from environmental variables. The goal is to be able to use [this action](https://github.com/aws-actions/configure-aws-credentials) through OIDC to login instead of hardcoded values.

I'm not entirely sold on making key id and access key not required, I can see how keeping them required but passing empty values could work.

### CODE REVIEW

**Comment by rlukata** [comment]
Any chance we can discuss this PR? Being able to use OIDC represents a significant improvement in the security posture.

**Comment by whywaita** [comment]
Looks good. But this repository's CI is a failure now.
I will fix it in #14. Please wait for it.

**Comment by whywaita** [comment]
I'm done. Please rebase again.

**Comment by rlukata** [comment]
any updates? would love to start using this action

**Comment by whywaita** [comment]
Thank you!

**Pull request merged**
